name: Deno

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test-panel:
    name: 🧪 Test Panel
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Setup repo
        uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Create env file
        run: |
          touch .env
          echo HOSTNAME=${{ secrets.HOSTNAME }} >> .env
          echo APIKEY=${{ secrets.APIKEY }} >> .env

      - name: Run tests
        run: deno test --allow-read --allow-env --env-file --allow-net src/test/test_panel.ts

  deploy:
    name: 🚀 Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - test-panel
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_DOMAIN }}
          port: 2022
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            sftp -o StrictHostKeyChecking=no -P ${{ secrets.FTP_PASSWORD }} <<EOF
            -mkdir -p /src/
            -put -r src/* /src/
            EOF
            echo "SFTP deployment completed"

  restart:
    name: 🔄 Restart
    permissions: write-all
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Pterodactyl-Restart
        uses: supercrafter100/Pterodactyl-Restart@v1.0
        with:
          PTE_PANEL_URL: ${{ secrets.FTP_DOMAIN }}
          PTE_BEARER_TOKEN: ${{ secrets.APIKEY }}
          PTE_PANEL_ID: ${{ secrets.PTE_PANEL_ID }}
